
skillMetadata:
  sections:
    - name: VLC Settings
      fields:
        - name: vlc_audio_path
          type: text
          label: path to audio files
          value: "/home/jsauwen/Musik"
          placeholder: path to audio files for VLC
    - name: Mopidy Settings
      fields:
        - type: label
          label: Just a little bit of extra info for the user to understand following settings
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
